platform :ios, '15.0'
use_frameworks!

target 'Pellazgo' do
  pod 'FirebaseCore'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseStorage'
  pod 'FirebaseCrashlytics'
  pod 'FirebaseAnalytics'
  pod 'Stripe'
  pod 'StripeApplePay'
  pod 'SDWebImageSwiftUI'
  pod 'Kingfisher'
  pod 'Alamofire'
  pod 'GoogleSignIn'
  pod 'Mixpanel'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
        config.build_settings['ENABLE_BITCODE'] = 'NO'
      end
    end
  end
end
